export const CATEGORIES = [
  { id: "all",        label: "All Owned" },
  { id: "Resources",  label: "Resources" },
  { id: "Mods",       label: "Mods" },
  { id: "Relics",     label: "Relics" },
  { id: "Arcanes",    label: "Arcanes" },
  { id: "Warframes",  label: "Warframes" },
  { id: "Primary",    label: "Primary" },
  { id: "Secondary",  label: "Secondary" },
  { id: "Melee",      label: "Melee" },
  { id: "Companions",       label: "Companions" },
  { id: "Archwing",         label: "Archwing" },
  { id: "Operator Weapons", label: "Operator Weapons" },
  { id: "Parts",            label: "Parts" },
  { id: "Blueprints", label: "Blueprints" },
  { id: "Miscellaneous", label: "Miscellaneous" },
  { id: "Sigils",     label: "Sigils" },
  { id: "Glyphs",     label: "Glyphs" },
  { id: "Skins",      label: "Skins" },
  { id: "Railjack",   label: "Railjack" },
];
